imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@CatalogPromotionPlugin/Resources/config/app/grid.yml" }
    - { resource: "@SitemapPlugin/Resources/config/config.yml" }
    - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }
    
    
    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
    - { resource: "emails.yml" }
    - { resource: "state_machine.yml" }
    - { resource: "resources.yml" }
    - { resource: "grids/grids.yml" }    
    - { resource: "grids/product.yml" }
    - { resource: "liip_config.yml" }    

twig:
    globals:
        version: %asset_version%

parameters:
    locale: ru_RU

sylius_product:
    resources:
        product:
            classes:
                repository: AppBundle\Repository\ProductRepositoryExt

sylius_order:
    resources:
        order:
            classes:
                controller: AppBundle\Controller\OrderRestoreController

sylius_shop:
    checkout_resolver:
        pattern: "%sylius.security.shop_regex%/checkout/"

framework:
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        handler_id: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "5.5"
        charset: UTF8
        mapping_types:
            json: json_array

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    
sylius_mailer:
    sender:
        name: Marinewool.ru
        address: no-reply@marinewool.ru

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
            
stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    selector: ""
    language: "ru"

ongr_elasticsearch:
    managers:
        default:
            index:
                index_name: sylius
            mappings:
                CatalogPromotionPlugin:
                    document_dir: ElasticSearch\Document

ongr_filter_manager:
    managers:
        search_list: #
            repository: es.manager.default.product

#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: []
#        allow_headers: []
#        allow_methods: []
#        expose_headers: []
#        max_age: 0
#        hosts: []
#        origin_regex: false
#        forced_allow_origin_value: ~
#    paths:
#        '^/shop-api/':
#            allow_origin: ['*']
#            allow_headers: ['Content-Type']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: ['^http://localhost:[0-9]+']
#            allow_headers: ['X-Custom-Auth']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#            hosts: ['^api\.']
sitemap:
    providers:
        products: true
        taxons: true
        static: false
#    template:             '@SitemapPlugin/show.xml.twig'
#    index_template:       '@SitemapPlugin/index.xml.twig'
#    exclude_taxon_root:   true
#    absolute_url:         true
#    hreflang:             true
    static_routes:
        - { route: sylius_shop_homepage, parameters: [], locales: [] }
        - { route: sylius_shop_contact_request, parameters: [], locales: [] }
        - { route: sylius_shop_news_index, parameters: [], locales: [] }        