winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                app_order_confirmation_admin:
                    on: ["new"]
                    do: ["@app.email_manager.order_confirmation_admin", "OrderComfirmAdminkEmail"]
                    args: ["object"]